### ISSUE TITLE
Message in chat is broken

### ISSUE THREAD

**Issue by FR33K1LL** [2called-chaos/csgo_gungame#2]
When in the lead, this message is printed in chat 

You are in the lead by 2,2:d levels on level {2}

**Comment by 2called-chaos** [comment]
Haven't worked on this in a while :) I noticed something similar in another plugin but never really figured out what the issue was.

Do other messages with variable numbers work? 

It comes from https://github.com/2called-chaos/csgo_gungame/blob/06a0311403f6203d3ad4aecf87ee889f62d62e7b/addons/sourcemod/scripting/gungame.sp#L498
 and the translation
https://github.com/2called-chaos/csgo_gungame/blob/06a0311403f6203d3ad4aecf87ee889f62d62e7b/addons/sourcemod/translations/gungame.txt#L154-L158

Not quite sure whether the variables are not replaced properly or the variables contain bogus info, I think I added them so I wouldn't be surprised :) But I can't see where the `2,2:d` should be coming from, is one of the "2"s the correct number of levels you are in the lead by?

I don't really have my setup going atm so I can't compile or test anything but if you can poke around a bit to narrow it down I might be able to help

**Comment by FR33K1LL** [comment]
Thanks for the reply, Chaos.

Other messages with variables work yes.

The first "2" is the correct number. Here are other examples, first number is always correct:

You are in the lead by 3,2:d levels on level {2}
You are in the lead by 4,2:d levels on level {2}
You are in the lead by 5,2:d levels on level {2}
You are in the lead by 6,2:d levels on level {2}

I'm not really a coder and have basic knowledge of coding. Any suggestions you make I can compile and test np, or even give you access to my server and sftp if required.

**Comment by 2called-chaos** [comment]
Hmm seems like the second variable might be invalid. Normally I poke to debug :D You can try to recompile and change the line 498 to something hardcoded as a test, e.g. 

```sp
CPrintToChat(CurrentLeader, "%t", "You are leading on level", 1, 2); 
```

If that displays correctly there is probably something wrong with newLevel

**Comment by FR33K1LL** [comment]
Asked some friends from the surftimer discord, damn curly brackets lol Tested it and it works now and made a PR.

![image](https://user-images.githubusercontent.com/63484108/130152973-29278536-511a-4bae-9767-e30585c140b3.png)

**Comment by 2called-chaos** [comment]
Oh man, those become invisible at some point. I guess I always used the other variant with weapon name so I never encountered the issue while coding this in. Thank you for the fix 👍
